# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: 'recursive'
          
      - name: Git Sumbodule Update
        run: git submodule update --remote --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build GFWList
        run: npm run build

      - name: Check Changes
        id: diff
        run: git diff-index --quiet HEAD -- || echo "::set-output name=has_changes::true"

      - name: Commit Changes
        if: ${{ steps.diff.outputs.has_changes }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "[build] `date`"
          git push origin master
