# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm run build
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
      - id: diff
        run: |
          git diff-index --quiet HEAD --
      - if: ${{ steps.diff.result }}
        run: |
          git commit -am "[build] `date`"
          git push origin master
